### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-q12ea#3]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by kasim393** [comment]
![image](https://user-images.githubusercontent.com/46850168/184350698-2eac9bbb-0399-4ef1-a03e-791ddac17a75.png)

**Comment by kasim393** [comment]
![image](https://user-images.githubusercontent.com/46850168/184382283-7f37ecd9-0ec3-4068-b8e2-f47b89e9ba12.png)
